apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hkh
resources:
- ../../base
images:
- name: admin-image
  newName: ghcr.io/robbertvdzon/hkh-admin
  newTag: sha-ec9ba58
- name: backend-image
  newName: ghcr.io/robbertvdzon/hkh-backend
  newTag: sha-ec9ba58
- name: frontend-image
  newName: ghcr.io/robbertvdzon/hkh-frontend
  newTag: sha-c0ad5f5
