apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hkh
resources:
- ../../base
- postgres-backup.yaml
images:
- name: admin-image
  newName: ghcr.io/robbertvdzon/hkh-admin
  newTag: sha-938962d
- name: backend-image
  newName: ghcr.io/robbertvdzon/hkh-backend
  newTag: sha-23bd56c
- name: frontend-image
  newName: ghcr.io/robbertvdzon/hkh-frontend
  newTag: sha-7e37ace
