apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hkh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/robbertvdzon/hkh.git
    targetRevision: main
    path: deploy/overlays/openshift
  destination:
    server: https://kubernetes.default.svc
    namespace: hkh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  revisionHistoryLimit: 5
