apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- preview-secret.yaml
- sealed-secret-ai-access.yaml
patches:
- target:
    group: bitnami.com
    version: v1alpha1
    kind: SealedSecret
    name: hkh-runtime
  patch: "$patch: delete\napiVersion: bitnami.com/v1alpha1\nkind: SealedSecret\nmetadata:\n\
    \  name: hkh-runtime"
- target:
    group: route.openshift.io
    version: v1
    kind: Route
    name: backend
  patch: "$patch: delete\napiVersion: route.openshift.io/v1\nkind: Route\nmetadata:\n\
    \  name: backend"
- path: agent-access-patch.yaml
- path: backend-memory.yaml
- path: frontend-memory.yaml
- path: admin-memory.yaml
- target:
    kind: StatefulSet
    name: database
  patch: "$patch: delete\napiVersion: apps/v1\nkind: StatefulSet\nmetadata:\n  name:\
    \ database\n"
- target:
    kind: Service
    name: database
  patch: "$patch: delete\napiVersion: v1\nkind: Service\nmetadata:\n  name: database\n"
- target:
    kind: PersistentVolumeClaim
    name: database-data
  patch: "$patch: delete\napiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n\
    \  name: database-data\n"
- path: central-postgres-patch.yaml
